// AUTO-GENERATED — DO NOT EDIT THIS FILE.
//
// Generated from github.com/kayushkin/principal-store @ 8b6362887d9a6438645f8aa0f9208e4a3f5602ff-dirty
// Source of truth: the Go types named in tygo.yaml.
// To regenerate: ./generate-ts.sh
//
// Any manual changes will be overwritten on the next generation run.

// Code generated by tygo. DO NOT EDIT.

//////////
// source: availability.go

/**
 * Availability is a human's declared working week, in their own zone. It is
 * the same shape as kanban-store's board BusinessHours on purpose, so the two
 * can be read by the same code, but it belongs to the person: a board in
 * Los Angeles can have a member in Amsterdam.
 * A principal with no Availability is *unknown*, and unknown is never
 * available. There is no default zone — a guessed zone would make a person
 * look free at 3am and an assignment made on that guess is worse than none.
 */
export interface Availability {
  tzid: string;
  days: string[];
  start: string;
  end: string;
}
/**
 * The reason vocabulary is served (GET /availability-reasons) so a caller
 * that branches on it never guesses the spelling. Exactly one reason applies
 * at any instant, checked in this order: a disabled principal is never
 * available whatever its hours; a principal with no schedule is unknown;
 * time off overrides the week; then the week itself decides.
 */
export const ReasonInHours = "in_hours";
/**
 * The reason vocabulary is served (GET /availability-reasons) so a caller
 * that branches on it never guesses the spelling. Exactly one reason applies
 * at any instant, checked in this order: a disabled principal is never
 * available whatever its hours; a principal with no schedule is unknown;
 * time off overrides the week; then the week itself decides.
 */
export const ReasonOffHours = "off_hours";
/**
 * The reason vocabulary is served (GET /availability-reasons) so a caller
 * that branches on it never guesses the spelling. Exactly one reason applies
 * at any instant, checked in this order: a disabled principal is never
 * available whatever its hours; a principal with no schedule is unknown;
 * time off overrides the week; then the week itself decides.
 */
export const ReasonTimeOff = "time_off";
/**
 * The reason vocabulary is served (GET /availability-reasons) so a caller
 * that branches on it never guesses the spelling. Exactly one reason applies
 * at any instant, checked in this order: a disabled principal is never
 * available whatever its hours; a principal with no schedule is unknown;
 * time off overrides the week; then the week itself decides.
 */
export const ReasonNoSchedule = "no_schedule";
/**
 * The reason vocabulary is served (GET /availability-reasons) so a caller
 * that branches on it never guesses the spelling. Exactly one reason applies
 * at any instant, checked in this order: a disabled principal is never
 * available whatever its hours; a principal with no schedule is unknown;
 * time off overrides the week; then the week itself decides.
 */
export const ReasonDisabled = "disabled";
/**
 * AvailabilityAnswer is what GET /principals/{id}/availability returns.
 * Available is true for exactly one reason, in_hours; the others say why not.
 */
export interface AvailabilityAnswer {
  principal_id: string;
  at: number /* int64 */;
  available: boolean;
  reason: string;
}
/**
 * TimeOff is one absence: a half-open range [starts_at, ends_at) in epoch
 * seconds. It sits beside the week rather than editing it, so a holiday does
 * not mean rewriting the schedule and restoring it after.
 */
export interface TimeOff {
  id: string;
  seq: number /* int64 */;
  principal_id: string;
  starts_at: number /* int64 */;
  ends_at: number /* int64 */;
  note: string;
  created_at: number /* int64 */;
}

//////////
// source: contact.go

/**
 * ContactResolution is what ResolveContact answers: the contact, and whether
 * this call is what created it. Created is not decoration — a caller that
 * suddenly creates a contact per message has a normalisation bug, and this is
 * the field that shows it.
 */
export interface ContactResolution {
  contact?: Principal;
  created: boolean;
}

//////////
// source: kind.go

export const KindHuman = "human";
export const KindGroup = "group";
/**
 * KindContact is someone outside this deployment who a ticket is *from*:
 * the requester who sent the mail. A contact never logs in, never holds a
 * grant, never joins a group and never administers anything — it exists so
 * a requester has an id, and twenty tickets from one person join on one
 * row instead of on a string that changes when they mail from their phone.
 */
export const KindContact = "contact";

//////////
// source: principal.go

/**
 * Principal is one human or one group.
 */
export interface Principal {
  id: string;
  seq: number /* int64 */;
  kind: string;
  display_name: string;
  email: string;
  disabled_at: number /* int64 */;
  created_at: number /* int64 */;
  updated_at: number /* int64 */;
  /**
   * IsAdministrator says this human administers the whole deployment: the
   * services that read it — kanban-store, grant-store, llm-bridge-server —
   * let an administrator past every per-resource check they make, so it is
   * the one fact that grants access to boards and sessions nobody granted.
   * Only a human can carry it; a group is a set of people, not someone who
   * acts. It says nothing on its own: a disabled principal is refused before
   * this is read.
   */
  is_administrator: boolean;
  /**
   * Availability is a human's declared working week in their own zone.
   * Absent means unknown, and unknown is never available — see
   * availability.go. A group never carries one.
   */
  availability?: Availability;
  /**
   * Computed on read by Get, ignored on write. Exactly one is present: a
   * human carries the groups it belongs to, a group carries its members.
   * omitzero rather than omitempty: a group with nobody in it still answers
   * "members": [] instead of leaving the caller to infer which kind it is.
   */
  groups?: Principal[];
  members?: Principal[];
}
/**
 * Patch carries only the fields a caller mentioned. kind is deliberately
 * absent — it is fixed at creation, because a group that became a human would
 * strand its memberships — and so is disabled_at, which moves only through
 * Disable and Enable so that removal is always an explicit act.
 */
export interface Patch {
  display_name?: string;
  email?: string;
  /**
   * Availability is raw because three shapes mean three things: absent
   * leaves the week alone, `null` or `{}` clears it, an object replaces it.
   */
  availability: unknown;
  /**
   * IsAdministrator promotes or demotes a human. Absent leaves it alone.
   */
  is_administrator?: boolean;
}
/**
 * Counts is the /health summary. Principals is every row, disabled included,
 * and equals Humans + Groups; Disabled is how many of those carry disabled_at.
 */
export interface Counts {
  principals: number /* int */;
  humans: number /* int */;
  groups: number /* int */;
  disabled: number /* int */;
}
/**
 * GroupMembership is what PUT /principals/{group}/members/{member} answers: the
 * pair that now exists, and whether this call created it (201) or found it
 * already there (200).
 */
export interface GroupMembership {
  group_id: string;
  member_id: string;
  created: boolean;
}

//////////
// source: server.go

